### ISSUE TITLE
XML configuration ConfigMap resource file not filtered

### ISSUE THREAD

**Issue by tipame** [eclipse/jkube#1291]
### Description
I create ConfigMap configuration like that:
```xml
<configuration>
  <filter>@</filter>
  <resources>
    <configMap>
      <name>configmap-test</name>
      <entries>
        <entry>
          <file>src/test/resources/test-application.yaml</file>
        </entry>
       </entries>
    </configMap>
  </resources>
</configuration>
```
In resource file  **test-application.yaml**:
```yaml
some.property: @property.placeholder@
```
This property is not resolved during resource goal execution (as expected).
Work only If same file content placed in  **/jkube/test-configmap.yaml**:
```yaml
data:
  test-application.yaml: |
    some.property: @property.placeholder@  
```

### Info

* Eclipse JKube version : 1.6.0, 1.5.1, 1.4.0
* Maven version (`mvn -v`) : 3.6.8

**Comment by manusa** [comment]
I don't think filtering is supported when using the `jkube-configmap-file`.

In your case, you are including a source file which in the end (if in Maven) should be processed by the Maven Resources Plugin. I understand that you are using this approach because this file is also used for other purposes. Why aren't you including the file that should be placed in `target/test-classes/` directory instead?

**Comment by tipame** [comment]
Ok. I can make filtration with resource plugin, but it's also can be done for all files in jkube directory. 
Doing so - we bring unnessesery copy of files as jkube already has filtration future (and copies files from jkube source dir to target). In my opinion it should be fixed.

**Comment by manusa** [comment]
The thing is that you are using a file that is not "handled by JKube". We can evaluate this, because it might make sense from a UX perspective (although I'm still not sure about this). 
From a technical perspective it doesn't because that resource is not handled by JKube and it's not a Fragment.

For me the question is, where else are you using that test resource? and why doesn't it need filtering for that other use case (or what's performing the filtering in that case)?

**Comment by tipame** [comment]
My motivation - is to use IDE formating futures wich are not working when file is part of configmap.yaml.
I have a number of platform dependend variables wich should be replaced during build.
